### ISSUE TITLE
Create View

### ISSUE THREAD

**Issue by smangham** [CorentinLouis/SPACE_labelling_tool#11]
* Single, persistent MPL canvas
* Registers for keypress events
* Feeds back to Presenter

**Comment by smangham** [comment]
Attempted to drop the 'kill then re-generate MPL window' behaviour by clearing the canvas; this caused drawing issues. Re-doing the kill then regenerate behaviour.

**Comment by smangham** [comment]
Issues for Elizabeth, running through the terminal, in Windows:
 * It froze on the choice box
```
Traceback (most recent call last): File "space_label.py", line 115, in <module> presenter.request_measurements() File "C:\Users\eliza\Desktop\git_folder\SPACE_labelling_tool-develop\spacelabel\presenters\__init__.py", line 70, in request_measurements self._measurements = self._view.select_measurements(measurements) File "C:\Users\eliza\Desktop\git_folder\SPACE_labelling_tool-develop\spacelabel\views\matplotlib.py", line 131, in select_measurements return multchoicebox( File "C:\Users\eliza\AppData\Local\Programs\Python\Python38\lib\site-packages\easygui\boxes\choice_box.py", line 71, in multchoicebox mb = ChoiceBox(msg, title, choices, preselect=preselect, File "C:\Users\eliza\AppData\Local\Programs\Python\Python38\lib\site-packages\easygui\boxes\choice_box.py", line 123, in __init__ preselect_list = make_list_or_none(preselect, cast_type=int) File "C:\Users\eliza\AppData\Local\Programs\Python\Python38\lib\site-packages\easygui\boxes\choice_box.py", line 95, in make_list_or_non 
```
* It also freezes on opening the plot window and showing all the data
  *  Corentin thinks this might be a backend issue
  * I'll test if it's a winpty issue for interactivity too

**Comment by smangham** [comment]
Works on Git Bash, Powershell and CMD on my machine. Python version maybe? Asking Elizabeth.

**Comment by smangham** [comment]
Fixed for Elizabeth by changing backend to QT5 on windows.
